server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gestion_evaluaciones_db}
    username: ${DB_USERNAME:evaluaciones_user}
    password: ${DB_PASSWORD:evaluaciones_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Swagger y OpenAPI bloqueados herméticamente en Producción
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: WARN
    com.institucion: INFO
